name: Check demo of projects

# Controls when the workflow will run
on:
  schedule: # “Every 6 hours”
    - cron: "0 */6 * * *"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Check domains
        run: |
          mkdir ./tests/screenshots
          npm run check-domains
      - name: Upload failure screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failure-screenshots
          path: ./tests/screenshots
          if-no-files-found: ignore

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./tests/screenshots
          if-no-files-found: ignore
